### ISSUE TITLE
Load error after dalamud update

### ISSUE THREAD

**Issue by Impurities** [a08381/Dalamud.SkipCutscene#2]
current log error as install fails/succeeds with error.

`2021-11-16 13:41:54.940 -04:00 [INF] [LOCALPLUGIN] Loading SkipCutscene.dll
2021-11-16 13:41:54.964 -04:00 [ERR] [LOCALPLUGIN] Error while loading SkipCutscene
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: This assembly is protected by an unregistered version of Eziriz's ".NET Reactor"! This assembly won't further work.
   at vvAxE0mujKuIkGCnA9.CoQ86RLIi1tYX7rbUE.OwKRA03XmeODs()
   at Plugins.a08381.SkipCutscene.SkipCutscene..ctor(DalamudPluginInterface pluginInterface) in D:\a\Dalamud.SkipCutscene\Dalamud.SkipCutscene\SkipCutscene\SkipCutscene.cs:line 27
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 321
   at Dalamud.Interface.Internal.Windows.PluginInstallerWindow.<>c__DisplayClass58_0.<DrawPluginControlButton>b__5() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstallerWindow.cs:line 1600
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2021-11-16 13:41:54.965 -04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMS0xMS0xNlQxMzo0MTo1NC45NjUyNTgzLTA0OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uRXhjZXB0aW9uOiBUaGlzIGFzc2VtYmx5IGlzIHByb3RlY3RlZCBieSBhbiB1bnJlZ2lzdGVyZWQgdmVyc2lvbiBvZiBFemlyaXoncyBcIi5ORVQgUmVhY3RvclwiISBUaGlzIGFzc2VtYmx5IHdvbid0IGZ1cnRoZXIgd29yay5cclxuICAgYXQgdnZBeEUwbXVqS3VJa0dDbkE5LkNvUTg2UkxJaTF0WVg3cmJVRS5Pd0tSQTAzWG1lT0RzKClcclxuICAgYXQgUGx1Z2lucy5hMDgzODEuU2tpcEN1dHNjZW5lLlNraXBDdXRzY2VuZS4uY3RvcihEYWxhbXVkUGx1Z2luSW50ZXJmYWNlIHBsdWdpbkludGVyZmFjZSkgaW4gRDpcXGFcXERhbGFtdWQuU2tpcEN1dHNjZW5lXFxEYWxhbXVkLlNraXBDdXRzY2VuZVxcU2tpcEN1dHNjZW5lXFxTa2lwQ3V0c2NlbmUuY3M6bGluZSAyN1xyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIE9iamVjdFtdIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBjb25zdHJ1Y3RvciwgQm9vbGVhbiB3cmFwRXhjZXB0aW9ucylcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZUNvbnN0cnVjdG9ySW5mby5JbnZva2UoT2JqZWN0IG9iaiwgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIsIEJpbmRlciBiaW5kZXIsIE9iamVjdFtdIHBhcmFtZXRlcnMsIEN1bHR1cmVJbmZvIGN1bHR1cmUpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLk1ldGhvZEJhc2UuSW52b2tlKE9iamVjdCBvYmosIE9iamVjdFtdIHBhcmFtZXRlcnMpXHJcbiAgIGF0IERhbGFtdWQuSW9DLkludGVybmFsLlNlcnZpY2VDb250YWluZXIuQ3JlYXRlKFR5cGUgb2JqZWN0VHlwZSwgT2JqZWN0W10gc2NvcGVkT2JqZWN0cykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW9DXFxJbnRlcm5hbFxcU2VydmljZUNvbnRhaW5lci5jczpsaW5lIDk1XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLkxvY2FsUGx1Z2luLkxvYWQoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxMb2NhbFBsdWdpbi5jczpsaW5lIDMyMSIsIkNvbnRleHQiOiJbTE9DQUxQTFVHSU5dIEVycm9yIHdoaWxlIGxvYWRpbmcgU2tpcEN1dHNjZW5lXG5TeXN0ZW0uUmVmbGVjdGlvbi5UYXJnZXRJbnZvY2F0aW9uRXhjZXB0aW9uOiBFeGNlcHRpb24gaGFzIGJlZW4gdGhyb3duIGJ5IHRoZSB0YXJnZXQgb2YgYW4gaW52b2NhdGlvbi5cclxuIC0tLT4gU3lzdGVtLkV4Y2VwdGlvbjogVGhpcyBhc3NlbWJseSBpcyBwcm90ZWN0ZWQgYnkgYW4gdW5yZWdpc3RlcmVkIHZlcnNpb24gb2YgRXppcml6J3MgXCIuTkVUIFJlYWN0b3JcIiEgVGhpcyBhc3NlbWJseSB3b24ndCBmdXJ0aGVyIHdvcmsuXHJcbiAgIGF0IHZ2QXhFMG11akt1SWtHQ25BOS5Db1E4NlJMSWkxdFlYN3JiVUUuT3dLUkEwM1htZU9EcygpXHJcbiAgIGF0IFBsdWdpbnMuYTA4MzgxLlNraXBDdXRzY2VuZS5Ta2lwQ3V0c2NlbmUuLmN0b3IoRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwbHVnaW5JbnRlcmZhY2UpIGluIEQ6XFxhXFxEYWxhbXVkLlNraXBDdXRzY2VuZVxcRGFsYW11ZC5Ta2lwQ3V0c2NlbmVcXFNraXBDdXRzY2VuZVxcU2tpcEN1dHNjZW5lLmNzOmxpbmUgMjdcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFN5c3RlbS5SdW50aW1lTWV0aG9kSGFuZGxlLkludm9rZU1ldGhvZChPYmplY3QgdGFyZ2V0LCBPYmplY3RbXSBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gY29uc3RydWN0b3IsIEJvb2xlYW4gd3JhcEV4Y2VwdGlvbnMpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5NZXRob2RCYXNlLkludm9rZShPYmplY3Qgb2JqLCBPYmplY3RbXSBwYXJhbWV0ZXJzKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZShUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXElvQ1xcSW50ZXJuYWxcXFNlcnZpY2VDb250YWluZXIuY3M6bGluZSA5NVxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5Mb2NhbFBsdWdpbi5Mb2FkKFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIHJlbG9hZGluZykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcTG9jYWxQbHVnaW4uY3M6bGluZSAzMjEifQ==
2021-11-16 13:41:54.965 -04:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: This assembly is protected by an unregistered version of Eziriz's ".NET Reactor"! This assembly won't further work.
   at vvAxE0mujKuIkGCnA9.CoQ86RLIi1tYX7rbUE.OwKRA03XmeODs()
   at Plugins.a08381.SkipCutscene.SkipCutscene..ctor(DalamudPluginInterface pluginInterface) in D:\a\Dalamud.SkipCutscene\Dalamud.SkipCutscene\SkipCutscene\SkipCutscene.cs:line 27
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 321
   at Dalamud.Interface.Internal.Windows.PluginInstallerWindow.<>c__DisplayClass58_0.<DrawPluginControlButton>b__5() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstallerWindow.cs:line 1600
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2021-11-16 13:41:54.966 -04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMS0xMS0xNlQxMzo0MTo1NC45NjYwMTI5LTA0OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uRXhjZXB0aW9uOiBUaGlzIGFzc2VtYmx5IGlzIHByb3RlY3RlZCBieSBhbiB1bnJlZ2lzdGVyZWQgdmVyc2lvbiBvZiBFemlyaXoncyBcIi5ORVQgUmVhY3RvclwiISBUaGlzIGFzc2VtYmx5IHdvbid0IGZ1cnRoZXIgd29yay5cclxuICAgYXQgdnZBeEUwbXVqS3VJa0dDbkE5LkNvUTg2UkxJaTF0WVg3cmJVRS5Pd0tSQTAzWG1lT0RzKClcclxuICAgYXQgUGx1Z2lucy5hMDgzODEuU2tpcEN1dHNjZW5lLlNraXBDdXRzY2VuZS4uY3RvcihEYWxhbXVkUGx1Z2luSW50ZXJmYWNlIHBsdWdpbkludGVyZmFjZSkgaW4gRDpcXGFcXERhbGFtdWQuU2tpcEN1dHNjZW5lXFxEYWxhbXVkLlNraXBDdXRzY2VuZVxcU2tpcEN1dHNjZW5lXFxTa2lwQ3V0c2NlbmUuY3M6bGluZSAyN1xyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJ1bnRpbWVNZXRob2RIYW5kbGUuSW52b2tlTWV0aG9kKE9iamVjdCB0YXJnZXQsIE9iamVjdFtdIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBjb25zdHJ1Y3RvciwgQm9vbGVhbiB3cmFwRXhjZXB0aW9ucylcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZUNvbnN0cnVjdG9ySW5mby5JbnZva2UoT2JqZWN0IG9iaiwgQmluZGluZ0ZsYWdzIGludm9rZUF0dHIsIEJpbmRlciBiaW5kZXIsIE9iamVjdFtdIHBhcmFtZXRlcnMsIEN1bHR1cmVJbmZvIGN1bHR1cmUpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLk1ldGhvZEJhc2UuSW52b2tlKE9iamVjdCBvYmosIE9iamVjdFtdIHBhcmFtZXRlcnMpXHJcbiAgIGF0IERhbGFtdWQuSW9DLkludGVybmFsLlNlcnZpY2VDb250YWluZXIuQ3JlYXRlKFR5cGUgb2JqZWN0VHlwZSwgT2JqZWN0W10gc2NvcGVkT2JqZWN0cykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW9DXFxJbnRlcm5hbFxcU2VydmljZUNvbnRhaW5lci5jczpsaW5lIDk1XHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLkxvY2FsUGx1Z2luLkxvYWQoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxMb2NhbFBsdWdpbi5jczpsaW5lIDMyMVxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5JbnRlcm5hbC5XaW5kb3dzLlBsdWdpbkluc3RhbGxlcldpbmRvdy48PmNfX0Rpc3BsYXlDbGFzczU4XzAuPERyYXdQbHVnaW5Db250cm9sQnV0dG9uPmJfXzUoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXEludGVybmFsXFxXaW5kb3dzXFxQbHVnaW5JbnN0YWxsZXJXaW5kb3cuY3M6bGluZSAxNjAwXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuVGFza3MuVGFzay5Jbm5lckludm9rZSgpXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuVGFza3MuVGFzay48PmMuPC5jY3Rvcj5iX18yNzdfMChPYmplY3Qgb2JqKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLkV4ZWN1dGlvbkNvbnRleHQuUnVuRnJvbVRocmVhZFBvb2xEaXNwYXRjaExvb3AoVGhyZWFkIHRocmVhZFBvb2xUaHJlYWQsIEV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dCwgQ29udGV4dENhbGxiYWNrIGNhbGxiYWNrLCBPYmplY3Qgc3RhdGUpXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiAtLS1cclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5FeGVjdXRpb25Db250ZXh0LlJ1bkZyb21UaHJlYWRQb29sRGlzcGF0Y2hMb29wKFRocmVhZCB0aHJlYWRQb29sVGhyZWFkLCBFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIENvbnRleHRDYWxsYmFjayBjYWxsYmFjaywgT2JqZWN0IHN0YXRlKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suRXhlY3V0ZVdpdGhUaHJlYWRMb2NhbChUYXNrJiBjdXJyZW50VGFza1Nsb3QsIFRocmVhZCB0aHJlYWRQb29sVGhyZWFkKSIsIkNvbnRleHQiOiJbUExVR0lOV10gUGx1Z2luIGluc3RhbGxlciB0aHJldyBhbiB1bmV4cGVjdGVkIGVycm9yXG5TeXN0ZW0uUmVmbGVjdGlvbi5UYXJnZXRJbnZvY2F0aW9uRXhjZXB0aW9uOiBFeGNlcHRpb24gaGFzIGJlZW4gdGhyb3duIGJ5IHRoZSB0YXJnZXQgb2YgYW4gaW52b2NhdGlvbi5cclxuIC0tLT4gU3lzdGVtLkV4Y2VwdGlvbjogVGhpcyBhc3NlbWJseSBpcyBwcm90ZWN0ZWQgYnkgYW4gdW5yZWdpc3RlcmVkIHZlcnNpb24gb2YgRXppcml6J3MgXCIuTkVUIFJlYWN0b3JcIiEgVGhpcyBhc3NlbWJseSB3b24ndCBmdXJ0aGVyIHdvcmsuXHJcbiAgIGF0IHZ2QXhFMG11akt1SWtHQ25BOS5Db1E4NlJMSWkxdFlYN3JiVUUuT3dLUkEwM1htZU9EcygpXHJcbiAgIGF0IFBsdWdpbnMuYTA4MzgxLlNraXBDdXRzY2VuZS5Ta2lwQ3V0c2NlbmUuLmN0b3IoRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwbHVnaW5JbnRlcmZhY2UpIGluIEQ6XFxhXFxEYWxhbXVkLlNraXBDdXRzY2VuZVxcRGFsYW11ZC5Ta2lwQ3V0c2NlbmVcXFNraXBDdXRzY2VuZVxcU2tpcEN1dHNjZW5lLmNzOmxpbmUgMjdcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFN5c3RlbS5SdW50aW1lTWV0aG9kSGFuZGxlLkludm9rZU1ldGhvZChPYmplY3QgdGFyZ2V0LCBPYmplY3RbXSBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gY29uc3RydWN0b3IsIEJvb2xlYW4gd3JhcEV4Y2VwdGlvbnMpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5NZXRob2RCYXNlLkludm9rZShPYmplY3Qgb2JqLCBPYmplY3RbXSBwYXJhbWV0ZXJzKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZShUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXElvQ1xcSW50ZXJuYWxcXFNlcnZpY2VDb250YWluZXIuY3M6bGluZSA5NVxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5Mb2NhbFBsdWdpbi5Mb2FkKFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIHJlbG9hZGluZykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcTG9jYWxQbHVnaW4uY3M6bGluZSAzMjFcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuSW50ZXJuYWwuV2luZG93cy5QbHVnaW5JbnN0YWxsZXJXaW5kb3cuPD5jX19EaXNwbGF5Q2xhc3M1OF8wLjxEcmF3UGx1Z2luQ29udHJvbEJ1dHRvbj5iX181KCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxJbnRlcm5hbFxcV2luZG93c1xcUGx1Z2luSW5zdGFsbGVyV2luZG93LmNzOmxpbmUgMTYwMFxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suSW5uZXJJbnZva2UoKVxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suPD5jLjwuY2N0b3I+Yl9fMjc3XzAoT2JqZWN0IG9iailcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5FeGVjdXRpb25Db250ZXh0LlJ1bkZyb21UaHJlYWRQb29sRGlzcGF0Y2hMb29wKFRocmVhZCB0aHJlYWRQb29sVGhyZWFkLCBFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIENvbnRleHRDYWxsYmFjayBjYWxsYmFjaywgT2JqZWN0IHN0YXRlKVxyXG4tLS0gRW5kIG9mIHN0YWNrIHRyYWNlIGZyb20gcHJldmlvdXMgbG9jYXRpb24gLS0tXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuRXhlY3V0aW9uQ29udGV4dC5SdW5Gcm9tVGhyZWFkUG9vbERpc3BhdGNoTG9vcChUaHJlYWQgdGhyZWFkUG9vbFRocmVhZCwgRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0LCBDb250ZXh0Q2FsbGJhY2sgY2FsbGJhY2ssIE9iamVjdCBzdGF0ZSlcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5UYXNrcy5UYXNrLkV4ZWN1dGVXaXRoVGhyZWFkTG9jYWwoVGFzayYgY3VycmVudFRhc2tTbG90LCBUaHJlYWQgdGhyZWFkUG9vbFRocmVhZCkifQ==
2021-11-16 13:41:56.456 -04:00 [INF] [LOCALPLUGIN] Unloading SkipCutscene.dll
2021-11-16 13:41:56.462 -04:00 [INF] [LOCALPLUGIN] Finished unloading SkipCutscene.dll

**Comment by a08381** [comment]
check branch `dist`
