### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by ghcruise** [a08381/Dalamud.SkipCutscene#5]
2022-02-02 10:37:53.828 +08:00 [INF] [PLUGINM] Loading plugin SkipCutscene
2022-02-02 10:37:53.887 +08:00 [INF] [LOCALPLUGIN] Loading SkipCutscene.dll
2022-02-02 10:37:53.937 +08:00 [ERR] [LOCALPLUGIN] Error while loading SkipCutscene
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: This assembly is protected by an unregistered version of Eziriz's ".NET Reactor"! This assembly won't further work.
   at d0oL3xUjRpnql6f6hv.aClEk45vbUktVXJcIW.EIZDi5AbH4L2X()
   at Plugins.a08381.SkipCutscene.SkipCutscene..ctor() in D:\a\Dalamud.SkipCutscene\Dalamud.SkipCutscene\SkipCutscene\SkipCutscene.cs:line 21
   --- End of inner exception stack trace ---

**Comment by a08381** [comment]
updated to 1.2.0.6.
